POC: Add Client (WIP)
Mirsaid04/Tarteeb.Importer pull request #8
Opened 2023-09-26 08:12 UTC by Mirsaid04

@JohnnySenior

2023-09-26 09:13 UTC, ElbekDeveloper requested changes

2023-09-26 09:13 UTC, ElbekDeveloper commented on Tarteeb.Importer/Services/Clients/ClientService.cs
> +            Message = "Invalid email"
Make message more informative

2023-09-29 14:18 UTC, ZafarUrakov requested changes
Correct the mistakes.

2023-09-29 14:18 UTC, ZafarUrakov commented on Tarteeb.Importer/Models/Clients/Exceptions/ClientDependencyException.cs
> +
Remove extra space! @Mirsaid04 @JohnnySenior

2023-09-29 14:18 UTC, ZafarUrakov commented on Tarteeb.Importer/Models/Clients/Exceptions/ClientDependencyValidationException.cs
> +
Remove extra space! @Mirsaid04 @JohnnySenior

2023-09-29 14:18 UTC, ZafarUrakov commented on Tarteeb.Importer/Models/Clients/Exceptions/ClientServiceException.cs
> +
Remove extra space! @Mirsaid04 @JohnnySenior

2023-09-29 14:18 UTC, ZafarUrakov commented on Tarteeb.Importer/Models/Clients/Exceptions/FailedServiceClientException.cs
> +
Remove extra space! @Mirsaid04 @JohnnySenior

2023-09-29 14:18 UTC, ZafarUrakov commented on Tarteeb.Importer/Models/Clients/Exceptions/LockedClientException.cs
> +
Remove extra space! @Mirsaid04 @JohnnySenior

2023-10-11 07:29 UTC, merged